// eslint-disable-next-line import/prefer-default-export
export const dataTable1 = [
	{
		id: 1,
		taskName: 'Hoàn tất mô tả phần mềm',
		subTaskCount: 3,
		subTaskList: [
			{
				id: 1,
				taskName: 'Lập bảng mô tả tính năng',
				owner: '',
				status: 'Đã hoàn thành',
				date: 'May 8',
				kpiPoint: 3,
				percentComplete: 100,
				departmentTaskName: 'Thành lập ban IT',
				taskType: 'Công việc cơ bản',
			},
			{
				id: 2,
				taskName: 'Tổng hợp các mẫu giao diện theo tính chất...',
				owner: '',
				status: 'Đang thực hiện',
				date: 'May 8',
				kpiPoint: 3,
				percentComplete: 0,
				departmentTaskName: 'Thành lập ban IT',
				taskType: 'Công việc cơ bản',
			},
			{
				id: 3,
				taskName: 'Lập bảng báo cáo',
				owner: '',
				status: 'Bế tắc',
				date: 'May 8',
				kpiPoint: 3,
				percentComplete: 0,
				departmentTaskName: 'Thành lập ban IT',
				taskType: 'Công việc cơ bản',
			},
		],
		owner: '',
		status: 'Đang thực hiện', // Đã hoàn thành Bế tắc
		dateStart: 'Apr 11',
		dateEnd: 'Jun 10',
		totalEntries: 20,
		totalKPIPoint: 40,
		percentComplete: 0,
		note: '',
	},
	{
		id: 2,
		taskName: 'Nhiệm vụ 2',
		subTaskCount: 3,
		subTaskList: [],
		owner: '',
		status: 'Đã hoàn thành', // Đã hoàn thành Bế tắc
		dateStart: 'Apr 11',
		dateEnd: 'Jun 10',
		totalEntries: 20,
		totalKPIPoint: 40,
		percentComplete: 0,
		note: '',
	},
];
